import { beforeEach, describe, expect, it, vi } from "vitest";

type Candidate = {
  id: string;
  slug: string;
  name: string;
  description: string;
  category: string | null;
};

type SupabaseState = {
  candidates: Candidate[] | null;
  pickError?: Error | null;
  claims: Record<string, boolean>;
  rpcCalls: Array<{ name: string; args?: unknown }>;
  updates: unknown[];
  candidateQuery: unknown[];
};

const mocks = vi.hoisted(() => ({
  state: undefined as SupabaseState | undefined,
  generateCover: vi.fn(),
  uploadCover: vi.fn(),
}));

vi.mock("../lib/supabase/server", () => ({
  supabaseService: () => createSupabase(mocks.state as SupabaseState),
}));

vi.mock("../lib/covers/generate", () => ({
  generateCover: mocks.generateCover,
}));

vi.mock("../lib/covers/upload", () => ({
  uploadCover: mocks.uploadCover,
}));

import { runCoverGeneration } from "../lib/covers/run";

function createState(overrides: Partial<SupabaseState> = {}): SupabaseState {
  return {
    candidates: [],
    pickError: null,
    claims: {},
    rpcCalls: [],
    updates: [],
    candidateQuery: [],
    ...overrides,
  };
}

function createSupabase(state: SupabaseState) {
  return {
    from(table: string) {
      if (table === "skill_stats") return createCandidateQuery(state);
      if (table === "skills") return createUpdateQuery(state);
      throw new Error(`unexpected table ${table}`);
    },
    rpc(name: string, args?: unknown) {
      state.rpcCalls.push({ name, args });
      if (name === "claim_skill_cover") {
        const skillId = (args as { p_skill_id: string }).p_skill_id;
        return Promise.resolve({ data: state.claims[skillId] ?? false, error: null });
      }
      if (name === "refresh_skill_stats") {
        return Promise.resolve({ data: true, error: null });
      }
      return Promise.resolve({ data: null, error: new Error(`unexpected rpc ${name}`) });
    },
  };
}

function createCandidateQuery(state: SupabaseState) {
  const query = {
    select(columns: string) {
      state.candidateQuery.push({ method: "select", columns });
      return query;
    },
    in(column: string, values: string[]) {
      state.candidateQuery.push({ method: "in", column, values });
      return query;
    },
    order(column: string, options: unknown) {
      state.candidateQuery.push({ method: "order", column, options });
      return query;
    },
    limit(count: number) {
      state.candidateQuery.push({ method: "limit", count });
      return query;
    },
    then<TResult1 = { data: Candidate[] | null; error: Error | null }, TResult2 = never>(
      onfulfilled?: ((value: { data: Candidate[] | null; error: Error | null }) => TResult1 | PromiseLike<TResult1>) | null,
      onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
    ) {
      return Promise.resolve({
        data: state.candidates,
        error: state.pickError ?? null,
      }).then(onfulfilled, onrejected);
    },
  };
  return query;
}

function createUpdateQuery(state: SupabaseState) {
  const update = {
    payload: undefined as unknown,
    filters: [] as Array<{ column: string; value: unknown }>,
    update(payload: unknown) {
      update.payload = payload;
      return update;
    },
    eq(column: string, value: unknown) {
      update.filters.push({ column, value });
      return update;
    },
    then<TResult1 = { error: null }, TResult2 = never>(
      onfulfilled?: ((value: { error: null }) => TResult1 | PromiseLike<TResult1>) | null,
      onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
    ) {
      state.updates.push({ payload: update.payload, filters: update.filters });
      return Promise.resolve({ error: null }).then(onfulfilled, onrejected);
    },
  };
  return update;
}

describe("runCoverGeneration", () => {
  beforeEach(() => {
    mocks.generateCover.mockReset();
    mocks.uploadCover.mockReset();
    mocks.state = createState();
  });

  it("returns candidate picking errors without attempting generation", async () => {
    mocks.state = createState({ pickError: new Error("select failed") });

    await expect(runCoverGeneration()).resolves.toEqual({
      attempted: 0,
      generated: 0,
      failed: 0,
      estimatedCostUsd: 0,
      errors: ["pick candidates: select failed"],
    });

    expect(mocks.generateCover).not.toHaveBeenCalled();
    expect(mocks.state.rpcCalls).toEqual([]);
  });

  it("claims pending covers, uploads generated bytes, and refreshes stats", async () => {
    const candidate = {
      id: "skill-1",
      slug: "demo",
      name: "Demo Skill",
      description: "Helps write tests",
      category: "coding",
    };
    mocks.state = createState({
      candidates: [candidate],
      claims: { "skill-1": true },
    });
    const bytes = Buffer.from("cover");
    mocks.generateCover.mockResolvedValue({ bytes, estimatedCostUsd: 0.1 });
    mocks.uploadCover.mockResolvedValue("https://blob.test/covers/demo.png");

    const stats = await runCoverGeneration({ limit: 1, quality: "medium", order: "first_seen" });

    expect(stats).toEqual({
      attempted: 1,
      generated: 1,
      failed: 0,
      estimatedCostUsd: 0.1,
      errors: [],
    });
    expect(mocks.state.candidateQuery).toContainEqual({ method: "order", column: "first_seen", options: { ascending: false } });
    expect(mocks.state.candidateQuery).toContainEqual({ method: "limit", count: 1 });
    expect(mocks.generateCover).toHaveBeenCalledWith({
      prompt: expect.stringContaining("Demo Skill"),
      quality: "medium",
    });
    expect(mocks.uploadCover).toHaveBeenCalledWith("demo", bytes);
    expect(mocks.state.updates).toHaveLength(1);
    expect(mocks.state.updates[0]).toMatchObject({
      payload: {
        cover_url: "https://blob.test/covers/demo.png",
        cover_status: "done",
        cover_error: null,
      },
      filters: [
        { column: "id", value: "skill-1" },
        { column: "cover_status", value: "generating" },
      ],
    });
    expect(mocks.state.rpcCalls).toContainEqual({ name: "refresh_skill_stats", args: undefined });
  });

  it("skips candidates that cannot be claimed", async () => {
    mocks.state = createState({
      candidates: [{
        id: "skill-1",
        slug: "demo",
        name: "Demo Skill",
        description: "Already taken",
        category: null,
      }],
      claims: { "skill-1": false },
    });

    const stats = await runCoverGeneration();

    expect(stats).toMatchObject({ attempted: 0, generated: 0, failed: 0 });
    expect(mocks.generateCover).not.toHaveBeenCalled();
    expect(mocks.state.updates).toEqual([]);
  });

  it("marks a claimed cover failed and includes charged generation cost when upload fails", async () => {
    mocks.state = createState({
      candidates: [{
        id: "skill-1",
        slug: "demo",
        name: "Demo Skill",
        description: "Upload failure",
        category: "utils",
      }],
      claims: { "skill-1": true },
    });
    mocks.generateCover.mockResolvedValue({ bytes: Buffer.from("cover"), estimatedCostUsd: 0.19 });
    mocks.uploadCover.mockRejectedValue(new Error("blob unavailable"));

    const stats = await runCoverGeneration({ quality: "high" });

    expect(stats).toEqual({
      attempted: 1,
      generated: 0,
      failed: 1,
      estimatedCostUsd: 0.19,
      errors: ["demo (charged $0.19): blob unavailable"],
    });
    expect(mocks.state.updates).toEqual([{
      payload: { cover_status: "failed", cover_error: "blob unavailable" },
      filters: [
        { column: "id", value: "skill-1" },
        { column: "cover_status", value: "generating" },
      ],
    }]);
  });
});
